WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 23, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
UnboundLocalError: local variable 'form' referenced before assignment
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 24, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
NameError: name 'form' is not defined
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
NameError: name 'data' is not defined
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
NameError: name 'data' is not defined
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
NameError: name 'data' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 27, in index
    return render_to_response('index.html', form, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than CourseForm.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 27, in index
    return render_to_response('index.html', 'form', RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than str.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 27, in index
    return render_to_response('index.html', 'form', RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than str.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 27, in index
    return render_to_response('index.html', {'form' : form}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 27, in index
    return render_to_response('index.html', {'form' : form}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/mce/urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 23, in index
    print("form is: ", form)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 23, in index
    print("form is: ", form)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 304, in as_p
    errors_on_separate_row=True,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 304, in as_p
    errors_on_separate_row=True,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 304, in as_p
    errors_on_separate_row=True,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    return render_to_response('index.html', {'form': form, 'data': data}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 304, in as_p
    errors_on_separate_row=True,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 86, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 221, in build_widget_attrs
    if widget.use_required_attribute(self.initial) and self.field.required and self.form.use_required_attribute:
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 702, in use_required_attribute
    return use_required_attribute and first_choice is not None and self._choice_has_empty_value(first_choice)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 688, in _choice_has_empty_value
    value, _ = choice
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 22, in index
    print("seeing what this does", form = CourseForm())
TypeError: 'form' is an invalid keyword argument for print()
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    course_lookup = CourseLookup(form.cleaned_data['course_code'])
KeyError: 'course_code'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 14, in index
    if form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 809, in valid_value
    for k, v in self.choices:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 29, in index
    return render_to_response('index.html', {'form': form, 'data': data, 'response': response}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 641, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 589, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
ValueError: too many values to unpack (expected 2)
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 29, in index
    return render_to_response('index.html', {'form': form, 'data': data, 'response': response}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 641, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 589, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 31, in index
    return render('index.html', {'form': form, 'data': data, 'response': response})
NameError: name 'render' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 31, in index
    return render('index.html', {'form': form, 'data': data, 'response': response})
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.7/site-packages/django/template/loaders/base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "/usr/local/lib/python3.7/site-packages/django/template/loaders/filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "/usr/local/lib/python3.7/site-packages/django/utils/_os.py", line 32, in safe_join
    final_path = abspath(join(base, *paths))
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 31, in index
    return render('index.html', {'form': form, 'data': data, 'response': response})
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.7/site-packages/django/template/loaders/base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "/usr/local/lib/python3.7/site-packages/django/template/loaders/filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "/usr/local/lib/python3.7/site-packages/django/utils/_os.py", line 32, in safe_join
    final_path = abspath(join(base, *paths))
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("form is: ", form.cleaned_data['course_code'])
AttributeError: 'CourseForm' object has no attribute 'cleaned_data'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("form is: ", form.cleaned_data[0])
AttributeError: 'CourseForm' object has no attribute 'cleaned_data'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 14, in index
    form = SearchForm(request.POST)
NameError: name 'SearchForm' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    testin = QueryDict(request.POST)
NameError: name 'QueryDict' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    testin = QueryDict(request.POST)
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 426, in __init__
    for key, value in limited_parse_qsl(query_string, **parse_qsl_kwargs):
  File "/usr/local/lib/python3.7/site-packages/django/utils/http.py", line 422, in limited_parse_qsl
    pairs = FIELDS_MATCH.split(qs, fields_limit)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("------request.post is: -----", request.POST.QueryDict)
AttributeError: 'QueryDict' object has no attribute 'QueryDict'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("------request.post is: -----", request.POST.QueryDict())
AttributeError: 'QueryDict' object has no attribute 'QueryDict'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    testin = QueryDict(request.POST)
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 426, in __init__
    for key, value in limited_parse_qsl(query_string, **parse_qsl_kwargs):
  File "/usr/local/lib/python3.7/site-packages/django/utils/http.py", line 422, in limited_parse_qsl
    pairs = FIELDS_MATCH.split(qs, fields_limit)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    testin = QueryDict(request.POST)
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 426, in __init__
    for key, value in limited_parse_qsl(query_string, **parse_qsl_kwargs):
  File "/usr/local/lib/python3.7/site-packages/django/utils/http.py", line 422, in limited_parse_qsl
    pairs = FIELDS_MATCH.split(qs, fields_limit)
TypeError: expected string or bytes-like object
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("-----form is:-----", form)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 393, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 654, in value_from_datadict
    getter = data.get
AttributeError: 'bytes' object has no attribute 'get'
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("-----form is:-----", form)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 393, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 654, in value_from_datadict
    getter = data.get
AttributeError: 'bytes' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("------request.post is: -----", request.body.loads())
AttributeError: 'bytes' object has no attribute 'loads'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    print("------request.post is: -----", request.loads())
AttributeError: 'WSGIRequest' object has no attribute 'loads'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    course_list = request.body['course_code']
TypeError: byte indices must be integers or slices, not str
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    course_list = request.body['course_code']
TypeError: byte indices must be integers or slices, not str
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 17, in index
    course_one = QueryDict.get_data('course_code', '0')
AttributeError: 'QueryDict' object has no attribute 'get_data'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 17, in index
    course_one = QueryDict.get('course_code')
AttributeError: 'bytes' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 24, in index
    if form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 393, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 654, in value_from_datadict
    getter = data.get
AttributeError: 'bytes' object has no attribute 'get'
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 24, in index
    if form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 393, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 654, in value_from_datadict
    getter = data.get
AttributeError: 'bytes' object has no attribute 'get'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 23, in index
    print("-----form after CourseForm is: -----", form)
UnboundLocalError: local variable 'form' referenced before assignment
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    test_dict = dict(QueryDict.list())
AttributeError: 'QueryDict' object has no attribute 'list'
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 15, in index
    test_dict = dict(QueryDict.list())
AttributeError: 'QueryDict' object has no attribute 'list'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 32, in index
    course_code = form.cleaned_data['course_code']
KeyError: 'course_code'
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 16, in index
    test_list = test_dict['course_code'].split(",")
AttributeError: 'list' object has no attribute 'split'
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    print("formset.errors is: ", formset.errors)
NameError: name 'formset' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("form is: ", form, "\n\n\n")
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 812, in valid_value
    for k2, v2 in v:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    print("form.is_valid is: ", form.is_valid())
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 812, in valid_value
    for k2, v2 in v:
ValueError: too many values to unpack (expected 2)
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    print("form.is_valid is: ", form.is_valid())
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 812, in valid_value
    for k2, v2 in v:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("form is: ", form, "\n\n\n")
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 812, in valid_value
    for k2, v2 in v:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 47, in index
    return render_to_response('index.html', {'form': form, 'data': data, 'response': response}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 641, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 589, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
ValueError: too many values to unpack (expected 2)
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 47, in index
    return render_to_response('index.html', {'form': form, 'data': data, 'response': response}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 641, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 589, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
ValueError: too many values to unpack (expected 2)
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 47, in index
    return render_to_response('index.html', {'form': form, 'data': data, 'response': response}, RequestContext(request))
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 641, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 589, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("form is: ", form, "\n\n\n")
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 809, in valid_value
    for k, v in self.choices:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 19, in index
    print("form is: ", form, "\n\n\n")
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 149, in clean
    self.validate(value)
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 799, in validate
    if value and not self.valid_value(value):
  File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 809, in valid_value
    for k, v in self.choices:
ValueError: too many values to unpack (expected 2)
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    if course_codes == "":
NameError: name 'course_codes' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 25, in index
    if course_codes == "":
NameError: name 'course_codes' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py", line 26, in index
    if course_codes == "":
NameError: name 'course_codes' is not defined
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
WARNING:django.request:Not Found: /ping.js
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/koryslaby/Desktop/MCE/GitHub/MCE-Project-for-MVAA-Frontend/www/home/form.py changed, reloading.
